'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { spawnSync } = require('node:child_process');
const repository = path.resolve(__dirname, '..');
const source = path.join(repository, 'src/main/windowsWfpLocalhostPoc.cs');
const fixture = path.join(repository, 'test/fixtures/wfp-egress-probe.cs');
const hash = file => crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const digest = value => crypto.createHash('sha256').update(value).digest('hex');
const quote = value => `'${value.replaceAll("'", "''")}'`;
const commandFileName = 'HUMAN-RUN-ELEVATED-COMMAND.txt';
const commandFileEncoding = 'UTF-8';
const commandFileNewline = 'CRLF';
const classifications = new Set(['STATIC_ONLY_NO_WFP_NO_NETWORK', 'EXACT_APP_LOCALHOST_MATRIX_PROVEN', 'MATRIX_NOT_PROVEN', 'UNKNOWN', 'HUMAN_ELEVATION_REQUIRED_FOR_WFP_PROOF', 'WFP_POLICY_INSTALLATION_BLOCKED', 'PROOF_OBJECTS_REMAIN']);
const displayNames = {
  SessionName: 'Munder WFP localhost proof session',
  CleanupSessionName: 'Munder WFP localhost cleanup query session',
  SublayerName: 'Munder WFP localhost proof sublayer',
  V4PermitName: 'Munder WFP localhost V4 permit',
  V4BlockName: 'Munder WFP localhost V4 catch-all block',
  V6BlockName: 'Munder WFP localhost V6 catch-all block',
};

function canonicalCommandBytes(command) {
  assert.equal(typeof command, 'string');
  assert.ok(command.length > 0);
  assert.doesNotMatch(command, /[\r\n]/, 'command must be a single logical line');
  return Buffer.from(command + '\r\n', 'utf8');
}

// The command file is the canonical handoff artifact: UTF-8 without BOM, exactly one
// terminal CRLF. Bytes are written exclusively, reread from disk, and only a byte- and
// hash-identical reread may be reported as verified.
function writeCommandFile(file, command) {
  const expected = canonicalCommandBytes(command);
  fs.writeFileSync(file, expected, { flag: 'wx' });
  const reread = fs.readFileSync(file);
  assert.equal(reread.length, expected.length, 'command file byte length must equal generated bytes');
  assert.equal(reread.compare(expected), 0, 'command file bytes must equal generated bytes');
  const sha256 = digest(reread), expectedSha256 = digest(expected);
  assert.equal(sha256, expectedSha256, 'command file hash must equal generated hash');
  assert.equal(reread.subarray(0, 3).equals(Buffer.from([0xEF, 0xBB, 0xBF])), false, 'command file must not carry a BOM');
  assert.equal(reread.subarray(-2).equals(Buffer.from('\r\n', 'utf8')), true, 'command file must end with CRLF');
  return { path: file, encoding: commandFileEncoding, newline: commandFileNewline, bom: false, byteLength: reread.length, sha256 };
}

const filterOffsets = { filterKey: 0, displayData: 16, flags: 32, providerKey: 40, providerData: 48, layerKey: 64, subLayerKey: 80, weight: 96, numFilterConditions: 112, filterCondition: 120, action: 128, rawContext: 152, providerContext: 152, reserved: 168, filterId: 176, effectiveWeight: 184 };
const filterLayout = { sizeOf: { Filter: 200, Display: 16, Blob: 16, Value: 16, Action: 20, Condition: 40 }, offsetOf: filterOffsets };
const diagnosticFields = ['filterKey', 'layerKey', 'subLayerKey', 'flags', 'providerKey', 'providerData.size', 'filterId', 'action.type', 'weight.type', 'weight.uint8', 'numFilterConditions'];
function exactKeys(value, keys) {
  assert.ok(value && typeof value === 'object' && !Array.isArray(value));
  assert.deepEqual(Object.keys(value).sort(), [...keys].sort());
}
function validateFilterDiagnostic(d, objects, index) {
  exactKeys(d, ['fields', 'mismatches', 'status']);
  exactKeys(d.fields, diagnosticFields);
  const expected = {
    filterKey: objects.filters[index], layerKey: index === 2 ? '4a72393b-319f-44bc-84c3-ba54dcb3b6b4' : 'c38d57d1-05a7-4c33-904f-7fbceee60e82', subLayerKey: objects.sublayer,
    flags: 0, providerKey: 'null', 'providerData.size': 0, 'action.type': index === 0 ? 0x1002 : 0x1001,
    'weight.type': 1, 'weight.uint8': index === 0 ? 15 : 1, numFilterConditions: index === 0 ? 4 : 1,
  };
  const mismatches = [];
  for (const name of diagnosticFields) {
    const f = d.fields[name], byte = name === 'weight.uint8';
    exactKeys(f, byte ? ['expected', 'actual', 'match', 'expectedApplicable', 'actualApplicable'] : ['expected', 'actual', 'match']);
    if (name !== 'filterId') assert.equal(f.expected, expected[name], `${name}: policy expectation`);
    for (const value of [f.expected, f.actual]) {
      if (['filterKey', 'layerKey', 'subLayerKey'].includes(name)) assert.match(value, /^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/);
      else if (name === 'providerKey') assert.ok(['null', 'non-null'].includes(value));
      else if (name === 'filterId') {
        assert.equal(typeof value, 'string'); assert.match(value, /^(0|[1-9][0-9]{0,19})$/); assert.ok(BigInt(value) <= 0xFFFFFFFFFFFFFFFFn);
      } else if (!(byte && value === null)) assert.ok(Number.isInteger(value) && value >= 0 && value <= (byte ? 255 : 0xFFFFFFFF));
    }
    if (name === 'filterId') assert.notEqual(f.expected, '0', 'add-returned filter ID required');
    if (byte) {
      assert.equal(f.expectedApplicable, d.fields['weight.type'].expected === 1);
      assert.equal(f.actualApplicable, d.fields['weight.type'].actual === 1);
      assert.equal(f.expected === null, !f.expectedApplicable);
      assert.equal(f.actual === null, !f.actualApplicable);
    }
    const match = f.expected === f.actual && (!byte || f.expectedApplicable === f.actualApplicable);
    assert.equal(f.match, match, `${name}: recomputed match`);
    if (!match) mismatches.push(name);
  }
  assert.deepEqual(d.mismatches, mismatches, 'exact ordered mismatch fields');
  assert.equal(d.status, mismatches.length ? 'MISMATCH' : 'MATCH');
  return mismatches;
}

function receipt(text) {
  assert.ok(Buffer.byteLength(text) <= 262144, 'receipt size bound');
  const r = JSON.parse(text.replace(/^\uFEFF/, ''));
  assert.equal(r.schema, 'wfp-localhost-proof');
  assert.ok(r.version === 1 || r.version === 2, 'supported receipt version');
  assert.equal(r.DNS_SERVICE_DELEGATION_CONTAINMENT, 'UNKNOWN');
  assert.ok(classifications.has(r.classification));
  // Version 1 is historical only; version 2 requires explicit representation evidence.
  if (r.version === 1) {
    assert.equal(r.filterLayout, undefined); assert.equal(r.filterDiagnostics, undefined);
  } else {
    assert.deepEqual(r.filterLayout, filterLayout);
    if (r.objects !== undefined || r.filters !== undefined || r.queryBeforeTraffic !== undefined || r.matrix !== undefined) assert.ok(Array.isArray(r.filterDiagnostics), 'v2 live evidence requires diagnostics');
  }
  if (r.filterDiagnostics !== undefined) {
    assert.ok(r.filterLayout, 'layout accompanies diagnostics');
    assert.ok(Array.isArray(r.filterDiagnostics) && r.filterDiagnostics.length <= 3);
    assert.ok(Array.isArray(r.objects?.filters) && r.objects.filters.length === 3);
    let failed = false;
    for (const [index, d] of r.filterDiagnostics.entries()) {
      assert.equal(failed, false, 'no installation after mismatch');
      failed = validateFilterDiagnostic(d, r.objects, index).length > 0;
      if (!failed && r.filters?.[index]) {
        const f = r.filters[index];
        for (const [field, key] of Object.entries({ filterKey: 'key', layerKey: 'layer', subLayerKey: 'sublayer', filterId: 'id', 'action.type': 'action', 'weight.uint8': 'weight' })) assert.equal(d.fields[field].actual, f[key]);
        assert.equal(d.fields.numFilterConditions.actual, f.conditions.length);
      }
    }
    if (failed) {
      assert.ok(['UNKNOWN', 'PROOF_OBJECTS_REMAIN'].includes(r.classification), 'mismatch cannot assert success');
      assert.equal(r.queryBeforeTraffic, undefined);
      assert.equal(r.matrix, undefined);
      assert.equal(r.filters.length, r.filterDiagnostics.length - 1);
    }
    if (r.classification === 'EXACT_APP_LOCALHOST_MATRIX_PROVEN') assert.equal(r.filterDiagnostics.length, 3);
    if (r.classification === 'STATIC_ONLY_NO_WFP_NO_NETWORK') assert.fail('static receipt cannot contain query evidence');
  } else if (r.filterLayout !== undefined && r.classification === 'EXACT_APP_LOCALHOST_MATRIX_PROVEN') assert.fail('new successful receipts require query evidence');
  // Historical receipts may predate stage evidence; validate it strictly when present.
  if (r.wfpFailure !== undefined) {
    const f = r.wfpFailure;
    assert.deepEqual(Object.keys(f).sort(), ['api', 'errorCode', 'errorHex', 'objectKey', 'role']);
    assert.ok(Number.isInteger(f.errorCode) && f.errorCode > 0 && f.errorCode <= 0xFFFFFFFF);
    assert.equal(f.errorCode, r.wfpErrorCode);
    assert.equal(f.errorHex, '0x' + f.errorCode.toString(16).toUpperCase().padStart(8, '0'));
    assert.match(f.objectKey, /^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/);
    const stages = {
      'proof-session': ['FwpmEngineOpen0', r.objects?.session],
      'proof-sublayer': ['FwpmSubLayerAdd0', r.objects?.sublayer],
      'v4-permit': ['FwpmFilterAdd0', r.objects?.filters?.[0]],
      'v4-catch-all-block': ['FwpmFilterAdd0', r.objects?.filters?.[1]],
      'v6-catch-all-block': ['FwpmFilterAdd0', r.objects?.filters?.[2]],
      'query-or-enumeration': ['UNSPECIFIED', '00000000-0000-0000-0000-000000000000'],
    };
    assert.ok(Object.hasOwn(stages, f.role), 'known failure stage required');
    assert.deepEqual([f.api, f.objectKey], stages[f.role]);
  }
  if (r.appIdBase64 !== undefined || r.appIdSha256 !== undefined) {
    assert.equal(typeof r.appIdBase64, 'string');
    const bytes = Buffer.from(r.appIdBase64, 'base64');
    assert.ok(bytes.length > 0);
    assert.equal(bytes.toString('base64'), r.appIdBase64);
    assert.equal(r.appIdSha256, crypto.createHash('sha256').update(bytes).digest('hex'));
  }
  if (r.cleanup?.status === 'ABSENT' || r.cleanup?.status === 'OBJECTS_REMAIN') {
    assert.equal(r.cleanup.enumerationComplete, true);
    assert.ok(Number.isSafeInteger(r.cleanup.remaining) && r.cleanup.remaining >= 0);
    assert.equal(r.WFP_PROOF_OBJECTS_REMAINING, r.cleanup.remaining);
    assert.equal(r.cleanup.status, r.cleanup.remaining === 0 ? 'ABSENT' : 'OBJECTS_REMAIN');
    for (const key of ['filtersEnumerated', 'sublayersEnumerated']) assert.ok(Number.isSafeInteger(r.cleanup[key]) && r.cleanup[key] >= 0);
    assert.match(r.cleanup.independentSession, /^[a-f0-9-]{36}$/);
    assert.notEqual(r.cleanup.independentSession, r.objects.session);
    if (r.engineCloseCode !== undefined) assert.equal(r.engineCloseCode, 0);
    if (r.cleanup.remaining > 0) assert.equal(r.classification, 'PROOF_OBJECTS_REMAIN');
  } else {
    assert.equal(r.WFP_PROOF_OBJECTS_REMAINING, undefined, 'unverified cleanup cannot claim a count');
    if (typeof r.cleanup === 'object' && r.cleanup !== null) {
      assert.ok(['UNKNOWN', 'UNVERIFIED_ELEVATION_REQUIRED'].includes(r.cleanup.status));
      assert.equal(r.cleanup.enumerationComplete, false);
      assert.equal(r.cleanup.remaining, undefined);
    }
  }
  if (r.classification === 'PROOF_OBJECTS_REMAIN') assert.equal(r.cleanup.status, 'OBJECTS_REMAIN');
  if (r.classification === 'HUMAN_ELEVATION_REQUIRED_FOR_WFP_PROOF') {
    assert.equal(r.wfpErrorCode, 5);
    assert.ok(['ABSENT', 'UNVERIFIED_ELEVATION_REQUIRED'].includes(r.cleanup.status));
    if (r.engineCloseCode !== undefined) assert.equal(r.engineCloseCode, 0);
  }
  if (r.classification === 'STATIC_ONLY_NO_WFP_NO_NETWORK' || r.classification === 'EXACT_APP_LOCALHOST_MATRIX_PROVEN') {
    for (const key of ['controllerSha256', 'probeSha256']) assert.match(r.identity[key], /^[a-f0-9]{64}$/);
    if (r.classification === 'STATIC_ONLY_NO_WFP_NO_NETWORK') assert.match(r.identity.fixtureSha256, /^[a-f0-9]{64}$/);
    else { assert.equal(r.identity.fixture, undefined); assert.equal(r.identity.fixtureSha256, undefined); }
    assert.ok(path.win32.isAbsolute(r.identity.probe));
    assert.equal(path.win32.normalize(r.identity.probe), r.identity.probe);
    assert.deepEqual(r.representation, { pointerSize: 8, filterSize: 200, conditionSize: 40, sublayerSize: 72, sessionSize: 72 });
  }
  if (r.classification === 'STATIC_ONLY_NO_WFP_NO_NETWORK') {
    assert.equal(r.cleanup, 'NOT_OPENED');
    for (const key of ['matrix', 'filters', 'objects', 'appIdBase64', 'appIdSha256', 'sessionQuery', 'WFP_PROOF_OBJECTS_REMAINING']) assert.equal(r[key], undefined);
  }
  if (r.classification === 'EXACT_APP_LOCALHOST_MATRIX_PROVEN') {
    assert.equal(r.queryBeforeTraffic, true);
    assert.equal(r.sublayerQuery, 'MATCH');
    assert.equal(r.sublayerDisplayName, displayNames.SublayerName);
    assert.equal(r.sessionQuery.displayName, displayNames.SessionName);
    assert.equal(r.cleanup.sessionQuery.status, 'MATCH');
    assert.equal(r.cleanup.sessionQuery.key, r.cleanup.independentSession);
    assert.equal(r.cleanup.sessionQuery.displayName, displayNames.CleanupSessionName);
    assert.equal(r.cleanup.status, 'ABSENT');
    assert.equal(r.engineCloseCode, 0);
    assert.equal(r.WFP_PROOF_OBJECTS_REMAINING, 0);
    assert.equal(r.sessionQuery.status, 'MATCH');
    assert.equal(r.sessionQuery.source, 'FwpmSessionEnum0');
    assert.equal(r.sessionQuery.key, r.objects.session);
    assert.equal(r.sessionQuery.flags, 1);
    assert.equal(r.sessionQuery.kernelMode, 0);
    assert.ok(Number.isInteger(r.sessionQuery.processId) && r.sessionQuery.processId > 0);
    assert.match(r.appIdSha256, /^[a-f0-9]{64}$/);
    assert.equal(new Set([r.objects.session, r.objects.sublayer, ...r.objects.filters]).size, 5);
    assert.equal(r.filters.length, 3);
    const app = 'd78e1e87-8644-4ea5-9437-d809ecefc971';
    for (const [index, f] of r.filters.entries()) {
      assert.equal(f.key, r.objects.filters[index]);
      assert.equal(f.displayName, [displayNames.V4PermitName, displayNames.V4BlockName, displayNames.V6BlockName][index]);
      assert.equal(f.sublayer, r.objects.sublayer);
      assert.equal(f.query, 'MATCH');
      assert.equal(f.layer, index === 2 ? '4a72393b-319f-44bc-84c3-ba54dcb3b6b4' : 'c38d57d1-05a7-4c33-904f-7fbceee60e82');
      assert.equal(f.action, index === 0 ? 0x1002 : 0x1001);
      assert.equal(f.weight, index === 0 ? 15 : 1);
      assert.equal(f.conditions.length, index === 0 ? 4 : 1);
      assert.deepEqual(f.conditions[0], { field: app, match: 0, type: 12, value: r.appIdBase64 });
    }
    assert.ok(BigInt(r.filters[0].effectiveWeight) > BigInt(r.filters[1].effectiveWeight));
    assert.deepEqual(r.matrix.map(row => row.label), ['tcp-approved', 'tcp-disallowed', 'tcp-ipv6', 'tcp-same-host', 'udp-disallowed']);
    for (const [index, row] of r.matrix.entries()) {
      assert.equal(row.pass, true);
      assert.equal(row.target.schema, 'wfp-local-target');
      assert.equal(row.target.address, row.address);
      assert.equal(row.target.port, row.port);
      assert.ok(Number.isInteger(row.port) && row.port >= 1024 && row.port <= 65535);
      assert.equal(row.target.protocol, index === 4 ? 'udp' : 'tcp');
      assert.equal(row.receiverObserved, index === 0);
      if (index < 4) {
        assert.equal(row.control, 'CONNECTED_AND_ACCEPTED');
        assert.equal(row.target.outcome, index === 0 ? 'CONNECTED' : 'SOCKET_ERROR');
        assert.equal(row.target.socketError, index === 0 ? 0 : 10013);
      } else {
        assert.equal(row.controlBefore, true); assert.equal(row.controlAfter, true);
        assert.equal(row.observationMilliseconds, 1000);
        assert.ok(row.target.outcome === 'SENT' || (row.target.outcome === 'SOCKET_ERROR' && row.target.socketError === 10013));
      }
    }
    assert.deepEqual(r.filters[0].conditions.slice(1), [
      { field: '3971ef2b-623e-4f9a-8cb1-6e79b806b9a7', match: 0, type: 1, value: '6' },
      { field: 'b235ae9a-1d64-49b8-a44c-5ff3d9095045', match: 0, type: 3, value: '2130706433' },
      { field: 'c35a604d-d22b-4e1a-91b4-68f674ee674b', match: 0, type: 2, value: String(r.matrix[0].port) },
    ]);
    assert.equal(r.matrix[0].address, '127.0.0.1');
    assert.equal(r.matrix[1].address, '127.0.0.1');
    assert.notEqual(r.matrix[0].port, r.matrix[1].port);
    assert.equal(r.matrix[2].address, '::1');
    assert.equal(r.matrix[3].address, r.sameHost.address);
    assert.equal(r.sameHost.operationalStatus, 'Up');
    assert.equal(r.sameHost.source, 'GetAllNetworkInterfaces.UnicastAddresses');
  }
  return r;
}

function staticChecks() {
  const controller = fs.readFileSync(source, 'utf8');
  const target = fs.readFileSync(fixture, 'utf8');
  // These are source policy checks, not runtime or WFP acceptance evidence.
  for (const forbidden of [/omp\.exe/i, /Verb\s*=\s*"runas"/i, /FwpmProviderAdd/, /FwpmFilterDelete/, /FwpmSubLayerDelete/, /HttpClient/, /Dns\./]) {
    assert.doesNotMatch(controller, forbidden); assert.doesNotMatch(target, forbidden);
  }
  for (const required of ['FwpmGetAppIdFromFileName0(executable', 'FwpmFilterGetByKey0', 'FwpmSubLayerGetByKey0', 'FwpmFilterEnum0', 'FwpmSubLayerEnum0', 'FwpmSessionEnum0', 'FwpmSessionDestroyEnumHandle0', 'appIdSha256', 'WFP_PROOF_OBJECTS_REMAINING', 'UNVERIFIED_ELEVATION_REQUIRED', 'FwpmFreeMemory0', 'CompileAssemblyFromFile(parameters, fixture)', 'flags = 1', 'DNS_SERVICE_DELEGATION_CONTAINMENT']) assert.ok(controller.includes(required), required);
  assert.equal(new Set(Object.values(displayNames)).size, 6);
  for (const [constant, name] of Object.entries(displayNames)) {
    assert.ok(name.length > 0 && name.length <= 128);
    assert.ok(controller.includes(`const string ${constant} = "${name}";`), constant);
  }
  for (const fragment of [
    'const int DisplayNameLimit = 128;',
    'Require(!String.IsNullOrEmpty(name) && name.Length <= DisplayNameLimit',
    'name = Marshal.StringToHGlobalUni(name)', 'public void Dispose() { Marshal.FreeHGlobal(Value.name); }',
    'display.name != IntPtr.Zero && !String.IsNullOrEmpty(expected) && expected.Length <= DisplayNameLimit',
    'Marshal.PtrToStringUni(display.name) == expected',
    'OpenSession(ref session, SessionName, "proof-session", out engine)',
    'OpenSession(ref session, CleanupSessionName, "cleanup-query-session", out engine)',
    'QuerySession(engine, session.key, SessionName)', 'QuerySession(engine, session.key, CleanupSessionName)',
    'AssertDisplay(actual.display, expectedName)', 'AssertDisplay(actual.display, SublayerName)', 'AssertDisplay(got.display, name)',
    'string name = permit ? V4PermitName : layer == V4 ? V4BlockName : V6BlockName;',
    'string role = permit ? "v4-permit" : layer == V4 ? "v4-catch-all-block" : "v6-catch-all-block";',
    'Code = code; Api = api; Role = role; ObjectKey = objectKey;',
    'receipt["wfpFailure"] = new { api = wfp.Api, role = wfp.Role, objectKey = wfp.ObjectKey, errorCode = wfp.Code, errorHex = "0x" + wfp.Code.ToString("X8") }',
    'Condition[] conditions = permit ? new Condition[] { C(App, new Value { type = 12, pointer = app }), C(Protocol, Number(1, 6)), C(Address, Number(3, 0x7f000001)), C(Port, Number(2, port)) } : new Condition[] { C(App, new Value { type = 12, pointer = app }) };',
    'weight = Number(1, permit ? 15U : 1U)', 'action = new Action { type = permit ? 0x1002U : 0x1001U }',
    'Sublayer layer = new Sublayer { key = sub, weight = 0x100 };',
    'Install(engine, sub, keys[0], V4, true, approved, app, diagnostics)', 'Install(engine, sub, keys[1], V4, false, approved, app, diagnostics)', 'Install(engine, sub, keys[2], V6, false, approved, app, diagnostics)',
    'string[] labels = { "tcp-approved", "tcp-disallowed", "tcp-ipv6", "tcp-same-host" };',
  ]) assert.ok(controller.includes(fragment), fragment);
  assert.equal((controller.match(/Session session = new Session \{ key = Guid.NewGuid\(\), flags = 1 \}/g) || []).length, 2);
  assert.equal((controller.match(/using \(NativeDisplay display = new NativeDisplay\(/g) || []).length, 3);
  assert.match(controller, /AssertDisplay\(session.display, name\);\s*Check\(FwpmEngineOpen0\(null, 10, IntPtr.Zero, ref session, out engine\), "FwpmEngineOpen0", role, session.key\)/);
  assert.match(controller, /AssertDisplay\(layer.display, SublayerName\);\s*Check\(FwpmSubLayerAdd0\(engine, ref layer, IntPtr.Zero\), "FwpmSubLayerAdd0", "proof-sublayer", sub\)/);
  assert.match(controller, /AssertDisplay\(wanted.display, name\);\s*Check\(FwpmFilterAdd0\(engine, ref wanted, IntPtr.Zero, out id\), "FwpmFilterAdd0", role, key\)/);
  for (const api of ['FwpmEngineOpen0', 'FwpmSubLayerAdd0', 'FwpmFilterAdd0']) assert.equal(controller.split(`${api}(`).length - 1, 2, `${api}: import and guarded call only`);
  for (const [identifier, guid] of Object.entries({ V4: 'c38d57d1-05a7-4c33-904f-7fbceee60e82', V6: '4a72393b-319f-44bc-84c3-ba54dcb3b6b4', App: 'd78e1e87-8644-4ea5-9437-d809ecefc971', Protocol: '3971ef2b-623e-4f9a-8cb1-6e79b806b9a7', Address: 'b235ae9a-1d64-49b8-a44c-5ff3d9095045', Port: 'c35a604d-d22b-4e1a-91b4-68f674ee674b' })) {
    assert.ok(controller.includes(`${identifier} = new Guid("${guid}")`), identifier);
  }
  for (const fragment of ['session.display = display.Value;', 'layer.display = display.Value;', 'Filter wanted = new Filter { key = key, display = display.Value, layer = layer, sublayer = sub,', 'finally { session.display = new Display(); }', 'finally { layer.display = new Display(); }', 'finally { Marshal.FreeHGlobal(block); }', 'Require(permitWeight > blockWeight, "Effective weight ordering mismatch")', 'matrix.Add(UdpRow(executable, udp))']) assert.ok(controller.includes(fragment), fragment);
  assert.throws(() => receipt('{}'));
  assert.throws(() => receipt('{"schema":"wfp-localhost-proof","version":1,"DNS_SERVICE_DELEGATION_CONTAINMENT":"PASS","classification":"UNKNOWN"}'));
  assert.throws(() => receipt('x'.repeat(262145)));
  const denied = { schema: 'wfp-localhost-proof', version: 1, DNS_SERVICE_DELEGATION_CONTAINMENT: 'UNKNOWN', classification: 'HUMAN_ELEVATION_REQUIRED_FOR_WFP_PROOF', wfpErrorCode: 5, cleanup: { status: 'UNVERIFIED_ELEVATION_REQUIRED', enumerationComplete: false } };
  assert.equal(receipt(JSON.stringify(denied)).classification, denied.classification);
  assert.equal(receipt('\uFEFF' + JSON.stringify(denied)).classification, denied.classification);
  assert.throws(() => receipt(JSON.stringify({ ...denied, WFP_PROOF_OBJECTS_REMAINING: 0 })));
  assert.throws(() => receipt(JSON.stringify({ ...denied, engineCloseCode: 5 })));
  assert.throws(() => receipt(JSON.stringify({ ...denied, wfpErrorCode: 6 })));
  assert.throws(() => receipt(JSON.stringify({ ...denied, appIdBase64: 'AA==', appIdSha256: '0'.repeat(64) })));
  assert.throws(() => receipt(JSON.stringify({ ...denied, cleanup: { status: 'ABSENT', enumerationComplete: false, remaining: 0 }, WFP_PROOF_OBJECTS_REMAINING: 0 })));
  assert.throws(() => receipt(JSON.stringify({ ...denied, classification: 'EXACT_APP_LOCALHOST_MATRIX_PROVEN' })));
  const absent = { ...denied, objects: { session: '11111111-1111-1111-1111-111111111111' }, cleanup: { status: 'ABSENT', enumerationComplete: true, remaining: 0, filtersEnumerated: 0, sublayersEnumerated: 0, independentSession: '22222222-2222-2222-2222-222222222222' }, WFP_PROOF_OBJECTS_REMAINING: 0 };
  assert.equal(receipt(JSON.stringify(absent)).WFP_PROOF_OBJECTS_REMAINING, 0);
  assert.throws(() => receipt(JSON.stringify({ ...absent, cleanup: { ...absent.cleanup, independentSession: absent.objects.session } })));
  const remaining = { ...absent, classification: 'PROOF_OBJECTS_REMAIN', cleanup: { ...absent.cleanup, status: 'OBJECTS_REMAIN', remaining: 1, filtersEnumerated: 1 }, WFP_PROOF_OBJECTS_REMAINING: 1 };
  assert.equal(receipt(JSON.stringify(remaining)).classification, 'PROOF_OBJECTS_REMAIN');
  assert.throws(() => receipt(JSON.stringify({ ...remaining, classification: denied.classification })));
  assert.throws(() => receipt(JSON.stringify({ ...remaining, WFP_PROOF_OBJECTS_REMAINING: 0 })));
  const objects = { session: '11111111-1111-1111-1111-111111111111', sublayer: '22222222-2222-2222-2222-222222222222', filters: ['33333333-3333-3333-3333-333333333333', '44444444-4444-4444-4444-444444444444', '55555555-5555-5555-5555-555555555555'] };
  const diagnostic = () => {
    const values = [objects.filters[0], 'c38d57d1-05a7-4c33-904f-7fbceee60e82', objects.sublayer, 0, 'null', 0, '18446744073709551615', 0x1002, 1, 15, 4];
    const fields = Object.fromEntries(diagnosticFields.map((name, i) => [name, { expected: values[i], actual: values[i], match: true }]));
    Object.assign(fields['weight.uint8'], { expectedApplicable: true, actualApplicable: true });
    return { fields, mismatches: [], status: 'MATCH' };
  };
  const diagnosticReceipt = d => ({ schema: 'wfp-localhost-proof', version: 2, DNS_SERVICE_DELEGATION_CONTAINMENT: 'UNKNOWN', classification: 'UNKNOWN', cleanup: 'NOT_OPENED', objects, filters: [], filterLayout, filterDiagnostics: [d] });
  assert.deepEqual(validateFilterDiagnostic(diagnostic(), objects, 0), []);
  const alternatives = ['66666666-6666-6666-6666-666666666666', '66666666-6666-6666-6666-666666666666', '66666666-6666-6666-6666-666666666666', 1, 'non-null', 1, '1', 0x1001, 2, 14, 3];
  for (const [i, name] of diagnosticFields.entries()) {
    const d = diagnostic(); d.fields[name].actual = alternatives[i]; d.fields[name].match = false;
    d.mismatches = [name]; d.status = 'MISMATCH';
    if (name === 'weight.type') {
      Object.assign(d.fields['weight.uint8'], { actual: null, actualApplicable: false, match: false }); d.mismatches.push('weight.uint8');
    }
    assert.deepEqual(validateFilterDiagnostic(d, objects, 0), d.mismatches);
    assert.deepEqual(receipt(JSON.stringify(diagnosticReceipt(d))).filterDiagnostics[0], d);
    const forged = structuredClone(d); forged.fields[name].match = true;
    assert.throws(() => receipt(JSON.stringify(diagnosticReceipt(forged))));
    assert.throws(() => receipt(JSON.stringify({ ...diagnosticReceipt(d), classification: 'EXACT_APP_LOCALHOST_MATRIX_PROVEN' })));
    const missing = diagnostic(); delete missing.fields[name];
    assert.throws(() => validateFilterDiagnostic(missing, objects, 0));
  }
  const multiple = diagnostic();
  for (const name of ['flags', 'providerData.size', 'numFilterConditions']) Object.assign(multiple.fields[name], { actual: 99, match: false });
  multiple.mismatches = ['flags', 'providerData.size', 'numFilterConditions']; multiple.status = 'MISMATCH';
  assert.deepEqual(receipt(JSON.stringify(diagnosticReceipt(multiple))).filterDiagnostics[0].mismatches, multiple.mismatches);
  for (const mutate of [
    d => { d.mismatches.pop(); }, d => { d.mismatches.reverse(); }, d => { d.status = 'MATCH'; },
    d => { d.fields.flags.expected = 99; d.fields.flags.match = true; }, d => { d.fields.providerKey.actual = '0x1234'; },
    d => { d.fields.filterId.actual = '18446744073709551616'; }, d => { d.fields.flags.actual = -1; },
    d => { d.fields['weight.uint8'].actualApplicable = false; }, d => { d.fields.flags.pointer = '0x1234'; },
    d => { d.fields.extra = {}; }, d => { d.extra = true; },
  ]) { const d = structuredClone(multiple); mutate(d); assert.throws(() => receipt(JSON.stringify(diagnosticReceipt(d)))); }
  assert.throws(() => receipt(JSON.stringify({ ...diagnosticReceipt(multiple), queryBeforeTraffic: true })));
  assert.throws(() => receipt(JSON.stringify({ ...diagnosticReceipt(multiple), filterDiagnostics: [multiple, diagnostic()] })));
  assert.throws(() => receipt(JSON.stringify({ ...diagnosticReceipt(multiple), filterDiagnostics: Array(4).fill(multiple) })));
  assert.throws(() => receipt(JSON.stringify({ ...diagnosticReceipt(multiple), filterLayout: { ...filterLayout, offsetOf: { ...filterOffsets, filterId: 160 } } })));
  assert.throws(() => receipt(JSON.stringify({ ...diagnosticReceipt(multiple), filterLayout: { ...filterLayout, pointer: '0x1234' } })));
  for (const mutation of [{ filterLayout: undefined }, { filterDiagnostics: undefined }, { filterLayout: undefined, filterDiagnostics: undefined }, { version: 1 }, { version: 3 }]) assert.throws(() => receipt(JSON.stringify({ ...diagnosticReceipt(multiple), ...mutation })));
  assert.ok(Buffer.byteLength(JSON.stringify({ ...diagnosticReceipt(diagnostic()), filterDiagnostics: Array(3).fill(diagnostic()) })) < 8192, 'bounded diagnostic payload');
  for (const name of diagnosticFields) assert.ok(controller.includes(`"${name}"`));
  for (const field of Object.keys(filterOffsets)) assert.ok(controller.includes(`"${field}"`));
  assert.match(controller, /Marshal\.OffsetOf\(typeof\(Filter\), fields\[i\]\)/);
  for (const type of Object.keys(filterLayout.sizeOf)) assert.ok(controller.includes(`${type} = Marshal.SizeOf(typeof(${type}))`));
  assert.match(controller, /FilterDiagnostic\(expectedFilter, got, id\);\s*Require\(diagnostics.Count < 3[^\n]+diagnostics.Add\(diagnostic\);\s*RequireFilterDiagnostic\(diagnostic\);\s*AssertDisplay\(got.display, name\)/);
  assert.match(controller, /Filter expectedFilter = wanted;[^\n]*\s*AssertDisplay\(wanted.display, name\);\s*Check\(FwpmFilterAdd0/);
  assert.ok(controller.includes('Require(mismatches.Count == 0, "Filter query mismatch: " + String.Join(", ", mismatches.ToArray()))'));
  assert.ok(controller.includes('receipt["filterDiagnostics"] = diagnostics;'));
  for (const fragment of ['Require(actual.field == expected.field && actual.match == 0 && actual.value.type == expected.value.type', 'Require(Equal(Bytes(actual.value.pointer), Bytes(app))', 'Require(actual.value.u32 == expected.value.u32', 'finally { if (queried != IntPtr.Zero) FwpmFreeMemory0(ref queried); }', 'close = FwpmEngineClose0(engine); receipt["engineCloseCode"] = close;', 'Require(close == 0, "Dynamic engine close failed")', 'receipt["cleanup"] = Absence(sub, keys, out remaining)', 'if (remaining != 0) receipt["classification"] = "PROOF_OBJECTS_REMAIN"']) assert.ok(controller.includes(fragment), fragment);
  for (const [api, role, objectKey] of [
    ['FwpmEngineOpen0', 'proof-session', objects.session],
    ['FwpmSubLayerAdd0', 'proof-sublayer', objects.sublayer],
    ...['v4-permit', 'v4-catch-all-block', 'v6-catch-all-block'].map((role, index) => ['FwpmFilterAdd0', role, objects.filters[index]]),
  ]) {
    const failure = { ...denied, objects, classification: 'WFP_POLICY_INSTALLATION_BLOCKED', wfpErrorCode: 0x80320023, wfpFailure: { api, role, objectKey, errorCode: 0x80320023, errorHex: '0x80320023' } };
    assert.deepEqual(receipt(JSON.stringify(failure)).wfpFailure, failure.wfpFailure);
    for (const mutation of [{ api: 'FwpmFilterDelete0' }, { role: 'unknown' }, { objectKey: '00000000-0000-0000-0000-000000000000' }, { errorCode: 5 }, { errorHex: '0x00000005' }]) {
      assert.throws(() => receipt(JSON.stringify({ ...failure, wfpFailure: { ...failure.wfpFailure, ...mutation } })));
    }
  }
  assert.match(controller, /static WindowsWfpLocalhostPoc\(\)\s*\{\s*if \(!SetDefaultDllDirectories\(0x00000800\) \|\| !SetDllDirectoryW\(""\)\) throw/);
  assert.deepEqual([...new Set([...controller.matchAll(/DllImport\("([^"]+)"/g)].map(match => match[1]))].sort(), ['fwpuclnt.dll', 'kernel32.dll']);
  assert.match(controller, /if \(!live\)[\s\S]*?Repository-owned invocation required[\s\S]*?CompileFixture\(fixture, executable\)/);
  assert.match(controller, /receipt\["identity"\] = live \? \(object\)new \{ controller = controller, controllerSha256 = Hash\(controller\), probe = executable, probeSha256 = Hash\(executable\) \}/);
  const inputs = { run: 'C:\\proof', executable: 'C:\\proof\\WindowsWfpLocalhostPoc.exe', probe: 'C:\\proof\\WfpEgressProbe.exe', controllerSha256: 'a'.repeat(64), probeSha256: 'b'.repeat(64), powershell: 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe', programData: 'C:\\ProgramData', proofId: 'c'.repeat(32) };
  const handoff = protectedHandoff(inputs), script = handoff.decodedPowerShell;
  assert.throws(() => protectedHandoff({ ...inputs, proofId: '../escape' }));
  assert.throws(() => protectedHandoff({ ...inputs, controllerSha256: 'invalid' }));
  assert.equal(Buffer.from(handoff.humanRunElevatedPowerShellCommand.split('-EncodedCommand ')[1], 'base64').toString('utf16le'), script);
  assert.match(handoff.previousCommand, /^INVALID_DO_NOT_EXECUTE:/);
  assert.equal(handoff.protectedStage, `C:\\ProgramData\\MunderWfpProof-${inputs.proofId}`);
  assert.equal(handoff.stageAclSddl, 'O:BAG:BAD:P(A;OICI;FA;;;BA)(A;OICI;FA;;;SY)');
  assert.doesNotMatch(script, /Start-Process|RunAs|Set-Acl|SetAccessControl|icacls|Remove-Item|\*/i);
  assert.equal((script.match(/\[IO.File\]::Copy\(/g) || []).length, 2);
  for (const [original, staged, digest] of [[inputs.executable, handoff.stagedController, inputs.controllerSha256], [inputs.probe, handoff.stagedProbe, inputs.probeSha256]]) {
    assert.ok(script.includes(`[IO.File]::Copy(${quote(original)},${quote(staged)},$false)`));
    for (const file of [original, staged]) assert.ok(script.includes(`(Get-FileHash -LiteralPath ${quote(file)} -Algorithm SHA256).Hash.ToLowerInvariant() -cne '${digest}'`));
  }
  const ordered = ["$security.SetSecurityDescriptorSddlForm(", '$attributes.Descriptor=$pin.AddrOfPinnedObject()', '[WfpProtectedStage]::CreateDirectoryW($stage,[ref]$attributes)', 'Staged frozen image mismatch', `& ${quote(handoff.stagedController)} --live ${inputs.controllerSha256} ${inputs.probeSha256}`, `Out-File -LiteralPath ${quote(handoff.stagedReceipt)}`, "throw 'Receipt byte bound'", '$r=ConvertFrom-Json', '$receiptHash=(Get-FileHash', "Write-Output ('WFP_RECEIPT_SHA256='", '[IO.FileMode]::CreateNew', '[IO.File]::Move(', '$finalized=$true', '[IO.Directory]::Delete($stage,$true)'];
  let previous = -1;
  for (const fragment of ordered) { const index = script.indexOf(fragment); assert.ok(index > previous, fragment); previous = index; }
  assert.equal((script.match(/& '.*?' --live/g) || []).length, 1);
  assert.equal((script.match(/\[IO.Directory\]::Delete\(/g) || []).length, 1);
  assert.ok(script.includes('if ($created -and $finalized) { [IO.Directory]::Delete($stage,$true) }'));
  for (const fragment of ['$rules.Count -ne 2', '$actual.AreAccessRulesProtected', 'S-1-5-32-544', 'S-1-5-18', '$length -gt 262144', '$bytes.Length -gt 262144', "$r.cleanup.status -ceq 'ABSENT'", '$r.cleanup.enumerationComplete -eq $true', '$r.cleanup.remaining -eq 0', '$r.WFP_PROOF_OBJECTS_REMAINING -eq 0', '$r.engineCloseCode -eq 0', 'exit $code']) assert.ok(script.includes(fragment), fragment);
  assert.ok(script.includes('$r.version -ne 2'));
  assert.ok(!script.includes('$r.version -ne 1'));
  for (const fragment of ["$r.PSObject.Properties.Name -notcontains 'filterLayout'", '$null -eq $r.filterLayout', "throw 'Missing v2 filter layout'", "'objects' -or $r.PSObject.Properties.Name -contains 'filters'", "'queryBeforeTraffic' -or $r.PSObject.Properties.Name -contains 'matrix'", 'if ($hasQueryEvidence)', "$r.PSObject.Properties.Name -notcontains 'filterDiagnostics'", '$r.filterDiagnostics -isnot [System.Array]', "throw 'Missing v2 filter diagnostics array'"]) assert.ok(script.includes(fragment), fragment);
  assert.ok(script.indexOf("throw 'Missing v2 filter diagnostics array'") < script.indexOf('$receiptHash=(Get-FileHash'), 'validate v2 evidence before receipt exposure');
  const canonical = canonicalCommandBytes(handoff.humanRunElevatedPowerShellCommand);
  assert.equal(canonical.subarray(0, 3).equals(Buffer.from([0xEF, 0xBB, 0xBF])), false, 'canonical command bytes must be BOM-free UTF-8');
  assert.equal(canonical.subarray(-2).equals(Buffer.from('\r\n', 'utf8')), true, 'canonical command bytes must end with a single CRLF');
  assert.equal(canonical.subarray(-4, -2).equals(Buffer.from('\r\n', 'utf8')), false, 'canonical command bytes must not end with a second newline');
  assert.equal(canonical.toString('utf8'), handoff.humanRunElevatedPowerShellCommand + '\r\n');
  assert.notEqual(digest(canonical), digest(Buffer.from(handoff.humanRunElevatedPowerShellCommand + '\n', 'utf8')), 'LF-only representation must not share the canonical hash');
  assert.throws(() => canonicalCommandBytes('line1\r\nline2'));
  const temporary = path.join(repository, '.tmp');
  fs.mkdirSync(temporary, { recursive: true });
  const scratch = fs.mkdtempSync(path.join(temporary, 'wfp-command-file-'));
  try {
    const scratchFile = path.join(scratch, commandFileName);
    const identity = writeCommandFile(scratchFile, handoff.humanRunElevatedPowerShellCommand);
    assert.equal(identity.path, scratchFile);
    assert.equal(identity.encoding, commandFileEncoding);
    assert.equal(identity.newline, commandFileNewline);
    assert.equal(identity.bom, false);
    assert.equal(identity.byteLength, canonical.length);
    assert.equal(identity.sha256, digest(canonical));
    assert.equal(hash(scratchFile), identity.sha256, 'reread bytes must hash to the bound sha256');
    assert.equal(fs.statSync(scratchFile).size, identity.byteLength);
    assert.throws(() => writeCommandFile(scratchFile, handoff.humanRunElevatedPowerShellCommand), /EEXIST/);
  } finally { fs.rmSync(scratch, { recursive: true, force: true }); }
  return { classification: 'STATIC_SOURCE_CHECKS_ONLY', controllerSourceSha256: hash(source), fixtureSourceSha256: hash(fixture), canonicalCommandFile: { fileName: commandFileName, encoding: commandFileEncoding, newline: commandFileNewline, decodedPayloadSha256: digest(Buffer.from(handoff.decodedPowerShell, 'utf8')), sha256: digest(canonical), byteLength: canonical.length }, live: 'NOT_RUN' };
}

function protectedHandoff({ run, executable, probe, controllerSha256, probeSha256, powershell, programData, proofId }) {
  assert.match(proofId, /^[a-f0-9]{32}$/);
  for (const digest of [controllerSha256, probeSha256]) assert.match(digest, /^[a-f0-9]{64}$/);
  for (const value of [run, executable, probe, powershell, programData]) {
    assert.ok(path.win32.isAbsolute(value) && !value.startsWith('\\\\'), 'local absolute path required');
    assert.equal(path.win32.normalize(value), value);
  }
  const stage = path.win32.join(programData, `MunderWfpProof-${proofId}`);
  const stagedController = path.win32.join(stage, 'WindowsWfpLocalhostPoc.exe');
  const stagedProbe = path.win32.join(stage, 'WfpEgressProbe.exe');
  const stagedReceipt = path.win32.join(stage, 'live-receipt.json');
  const liveReceipt = path.win32.join(run, 'live-receipt.json');
  const exposureTemp = path.win32.join(run, `live-receipt-${proofId}.tmp`);
  const sddl = 'O:BAG:BAD:P(A;OICI;FA;;;BA)(A;OICI;FA;;;SY)';
  const liveScript = `
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { throw 'Human must open an elevated PowerShell explicitly' }
$stage=${quote(stage)}
if ([Environment]::GetFolderPath([Environment+SpecialFolder]::CommonApplicationData) -cne ${quote(programData)}) { throw 'ProgramData identity mismatch' }
function NoLinks([string]$p) { while ($p) { if (([IO.File]::GetAttributes($p) -band [IO.FileAttributes]::ReparsePoint) -ne 0) { throw 'Reparse point rejected' }; $p=[IO.Path]::GetDirectoryName($p) } }
NoLinks ${quote(programData)}
NoLinks ${quote(run)}
if (-not [IO.Directory]::Exists(${quote(run)})) { throw 'Existing proof directory required' }
if ([IO.Directory]::Exists($stage) -or [IO.File]::Exists($stage)) { throw 'Stage already exists' }
Add-Type -TypeDefinition @'
using System;
using System.Runtime.InteropServices;
public static class WfpProtectedStage {
  [StructLayout(LayoutKind.Sequential)] public struct Attributes { public int Length; public IntPtr Descriptor; public int Inherit; }
  [DllImport("kernel32.dll", CharSet=CharSet.Unicode, ExactSpelling=true, SetLastError=true)]
  [return: MarshalAs(UnmanagedType.Bool)] public static extern bool CreateDirectoryW(string path, ref Attributes attributes);
}
'@
$security=New-Object Security.AccessControl.DirectorySecurity
$security.SetSecurityDescriptorSddlForm('${sddl}')
$descriptor=$security.GetSecurityDescriptorBinaryForm()
$pin=[Runtime.InteropServices.GCHandle]::Alloc($descriptor,[Runtime.InteropServices.GCHandleType]::Pinned)
$created=$false
$finalized=$false
try {
  $attributes=New-Object WfpProtectedStage+Attributes
  $attributes.Length=[Runtime.InteropServices.Marshal]::SizeOf($attributes)
  $attributes.Descriptor=$pin.AddrOfPinnedObject()
  if (-not [WfpProtectedStage]::CreateDirectoryW($stage,[ref]$attributes)) { throw ('Exclusive protected stage creation failed: '+[Runtime.InteropServices.Marshal]::GetLastWin32Error()) }
  $created=$true
} finally { $pin.Free() }
try {
  NoLinks $stage
  $actual=[IO.Directory]::GetAccessControl($stage)
  if (-not $actual.AreAccessRulesProtected) { throw 'Unprotected stage DACL' }
  $rules=@($actual.GetAccessRules($true,$true,[Security.Principal.SecurityIdentifier]))
  if ($rules.Count -ne 2) { throw 'Unexpected stage ACE count' }
  foreach ($sid in @('S-1-5-32-544','S-1-5-18')) {
    $rule=@($rules | Where-Object { $_.IdentityReference.Value -eq $sid })
    if ($rule.Count -ne 1 -or $rule[0].IsInherited -or $rule[0].AccessControlType -ne 'Allow' -or $rule[0].FileSystemRights -ne [Security.AccessControl.FileSystemRights]::FullControl -or $rule[0].InheritanceFlags -ne ([Security.AccessControl.InheritanceFlags]::ContainerInherit -bor [Security.AccessControl.InheritanceFlags]::ObjectInherit) -or $rule[0].PropagationFlags -ne [Security.AccessControl.PropagationFlags]::None) { throw 'Unexpected stage ACE' }
  }
  NoLinks ${quote(executable)}
  NoLinks ${quote(probe)}
  if ((Get-FileHash -LiteralPath ${quote(executable)} -Algorithm SHA256).Hash.ToLowerInvariant() -cne '${controllerSha256}' -or (Get-FileHash -LiteralPath ${quote(probe)} -Algorithm SHA256).Hash.ToLowerInvariant() -cne '${probeSha256}') { throw 'Original frozen image mismatch' }
  [IO.File]::Copy(${quote(executable)},${quote(stagedController)},$false)
  [IO.File]::Copy(${quote(probe)},${quote(stagedProbe)},$false)
  if ((Get-FileHash -LiteralPath ${quote(stagedController)} -Algorithm SHA256).Hash.ToLowerInvariant() -cne '${controllerSha256}' -or (Get-FileHash -LiteralPath ${quote(stagedProbe)} -Algorithm SHA256).Hash.ToLowerInvariant() -cne '${probeSha256}') { throw 'Staged frozen image mismatch' }
  Push-Location -LiteralPath $stage
  try { & ${quote(stagedController)} --live ${controllerSha256} ${probeSha256} | Out-File -LiteralPath ${quote(stagedReceipt)} -Encoding utf8; $code=$LASTEXITCODE } finally { Pop-Location }
  $length=([IO.FileInfo]${quote(stagedReceipt)}).Length
  if ($length -le 0 -or $length -gt 262144) { throw 'Receipt byte bound' }
  $text=[IO.File]::ReadAllText(${quote(stagedReceipt)})
  $r=ConvertFrom-Json -InputObject $text
  if ($r.schema -cne 'wfp-localhost-proof' -or $r.version -ne 2 -or $r.DNS_SERVICE_DELEGATION_CONTAINMENT -cne 'UNKNOWN' -or @('EXACT_APP_LOCALHOST_MATRIX_PROVEN','MATRIX_NOT_PROVEN','UNKNOWN','HUMAN_ELEVATION_REQUIRED_FOR_WFP_PROOF','WFP_POLICY_INSTALLATION_BLOCKED','PROOF_OBJECTS_REMAIN') -cnotcontains $r.classification) { throw 'Invalid live receipt' }
  if ($r.PSObject.Properties.Name -notcontains 'filterLayout' -or $null -eq $r.filterLayout) { throw 'Missing v2 filter layout' }
  $hasQueryEvidence=($r.PSObject.Properties.Name -contains 'objects' -or $r.PSObject.Properties.Name -contains 'filters' -or $r.PSObject.Properties.Name -contains 'queryBeforeTraffic' -or $r.PSObject.Properties.Name -contains 'matrix')
  if ($hasQueryEvidence) {
    if ($r.PSObject.Properties.Name -notcontains 'filterDiagnostics' -or $r.filterDiagnostics -isnot [System.Array]) { throw 'Missing v2 filter diagnostics array' }
  }
  if ($r.PSObject.Properties.Name -contains 'identity') {
    if ($r.identity.controller -cne ${quote(stagedController)} -or $r.identity.probe -cne ${quote(stagedProbe)} -or $r.identity.controllerSha256 -cne '${controllerSha256}' -or $r.identity.probeSha256 -cne '${probeSha256}') { throw 'Receipt staged identity mismatch' }
  } elseif ($code -eq 0) { throw 'Missing receipt identity' }
  $success=$false
  if ($code -eq 0) {
    try { $success=($r.classification -ceq 'EXACT_APP_LOCALHOST_MATRIX_PROVEN' -and $r.cleanup.status -ceq 'ABSENT' -and $r.cleanup.enumerationComplete -eq $true -and $r.cleanup.remaining -eq 0 -and $r.WFP_PROOF_OBJECTS_REMAINING -eq 0 -and $r.engineCloseCode -eq 0) } catch { $success=$false }
  }
  $receiptHash=(Get-FileHash -LiteralPath ${quote(stagedReceipt)} -Algorithm SHA256).Hash.ToLowerInvariant()
  Write-Output ('WFP_RECEIPT_SHA256='+$receiptHash)
  NoLinks ${quote(run)}
  $bytes=[IO.File]::ReadAllBytes(${quote(stagedReceipt)})
  if ($bytes.Length -gt 262144) { throw 'Receipt copy bound' }
  $output=[IO.File]::Open(${quote(exposureTemp)},[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None)
  try { $output.Write($bytes,0,$bytes.Length); $output.Flush($true) } finally { $output.Dispose() }
  [IO.File]::Move(${quote(exposureTemp)},${quote(liveReceipt)})
  $finalized=$true
  if ($code -eq 0 -and -not $success) { throw 'Zero exit without proven classification and cleanup' }
  if ($success) { Write-Output 'WFP_HANDOFF_SUCCESS' }
} finally {
  if ($created -and $finalized) { [IO.Directory]::Delete($stage,$true) }
  elseif ($created) { Write-Warning ('Evidence retained in exact protected stage: '+$stage) }
}
exit $code
`.trim();
  const command = `& ${quote(powershell)} -NoLogo -NoProfile -NonInteractive -EncodedCommand ${Buffer.from(liveScript, 'utf16le').toString('base64')}`;
  return { proofId, previousCommand: 'INVALID_DO_NOT_EXECUTE: prior repository-direct elevation command is superseded', protectedStage: stage, stageAclSddl: sddl, stagedController, stagedProbe, stagedControllerSha256: controllerSha256, stagedProbeSha256: probeSha256, stagedReceipt, liveReceipt, exposureTemp, receiptHashOutput: 'WFP_RECEIPT_SHA256=<lowercase SHA256 of staged receipt bytes before exposure>', humanRunElevatedPowerShellCommand: command, decodedPowerShell: liveScript };
}

function prepare() {
  assert.equal(process.platform, 'win32', 'prepare requires Windows');
  assert.equal(process.arch, 'x64', 'prepare requires x64 Node');
  const temporary = path.join(repository, '.tmp');
  fs.mkdirSync(temporary, { recursive: true });
  const run = fs.mkdtempSync(path.join(temporary, 'windows-wfp-localhost-poc-'));
  const executable = path.join(run, 'WindowsWfpLocalhostPoc.exe');
  const probe = path.join(run, 'WfpEgressProbe.exe');
  const powershell = path.join(process.env.SystemRoot, 'System32/WindowsPowerShell/v1.0/powershell.exe');
  const environment = { SystemRoot: process.env.SystemRoot, TEMP: run, TMP: run, POWERSHELL_TELEMETRY_OPTOUT: '1', POWERSHELL_UPDATECHECK: 'Off' };
  const invoke = (name, program, args) => {
    const result = spawnSync(program, args, { cwd: repository, env: environment, encoding: 'utf8', timeout: 60000, maxBuffer: 262144, windowsHide: true });
    fs.writeFileSync(path.join(run, `${name}.json`), JSON.stringify({ status: result.status, signal: result.signal, error: result.error?.message, stdout: result.stdout, stderr: result.stderr }, null, 2));
    assert.equal(result.error, undefined, `retained: ${run}`);
    assert.equal(result.status, 0, `retained: ${run}; ${result.stdout}; ${result.stderr}`);
    return result.stdout;
  };
  try {
    const script = `$ErrorActionPreference='Stop'; if (([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { throw 'Prepare requires non-admin' }; Add-Type -Path ${quote(source)} -ReferencedAssemblies 'System.dll','System.Web.Extensions.dll','Microsoft.CSharp.dll' -OutputAssembly ${quote(executable)} -OutputType ConsoleApplication -ErrorAction Stop`;
    invoke('compile', powershell, ['-NoLogo', '-NoProfile', '-NonInteractive', '-EncodedCommand', Buffer.from(script, 'utf16le').toString('base64')]);
    const prepared = receipt(invoke('prepare', executable, ['--prepare']));
    assert.equal(prepared.identity.controller, executable);
    assert.equal(prepared.identity.probe, probe);
    const controllerSha256 = hash(executable), probeSha256 = hash(probe);
    assert.equal(prepared.identity.controllerSha256, controllerSha256);
    assert.equal(prepared.identity.probeSha256, probeSha256);
    receipt(invoke('static', executable, ['--static', controllerSha256, probeSha256]));
    for (const [name, args] of [['reject-empty', []], ['reject-appid', ['--live', '--app-id', 'arbitrary']], ['reject-extra', ['--static', controllerSha256, probeSha256, 'extra']]]) {
      const result = spawnSync(executable, args, { cwd: run, env: environment, encoding: 'utf8', timeout: 5000, maxBuffer: 262144, windowsHide: true });
      fs.writeFileSync(path.join(run, `${name}.json`), JSON.stringify({ status: result.status, error: result.error?.message, stdout: result.stdout, stderr: result.stderr }, null, 2));
      assert.equal(result.error, undefined); assert.equal(result.status, 2);
      const rejected = receipt(result.stdout); assert.equal(rejected.classification, 'UNKNOWN'); assert.equal(rejected.cleanup, 'NOT_OPENED'); assert.equal(rejected.objects, undefined);
    }
    const handoff = protectedHandoff({ run, executable, probe, controllerSha256, probeSha256, powershell, programData: process.env.ProgramData, proofId: crypto.randomBytes(16).toString('hex') });
    const commandFile = path.join(run, commandFileName);
    const commandFileIdentity = writeCommandFile(commandFile, handoff.humanRunElevatedPowerShellCommand);
    const decoded = Buffer.from(handoff.humanRunElevatedPowerShellCommand.split('-EncodedCommand ')[1], 'base64');
    assert.equal(decoded.toString('utf16le'), handoff.decodedPowerShell, 'manifest command must decode to decodedPowerShell');
    const decodedPayloadSha256 = digest(Buffer.from(handoff.decodedPowerShell, 'utf8'));
    const manifest = { schema: 'wfp-localhost-prepare', version: 2, run, controller: executable, controllerSha256, probe, probeSha256, controllerSourceSha256: hash(source), fixtureSourceSha256: hash(fixture), live: 'NOT_RUN', invocationCount: 1, ...handoff, commandFile: { path: commandFileIdentity.path, encoding: commandFileIdentity.encoding, newline: commandFileIdentity.newline, bom: commandFileIdentity.bom, byteLength: commandFileIdentity.byteLength, sha256: commandFileIdentity.sha256, decodedPayloadSha256 } };
    fs.writeFileSync(path.join(run, 'frozen-manifest.json'), JSON.stringify(manifest, null, 2), { flag: 'wx' });
    return manifest;
  } catch (error) {
    fs.writeFileSync(path.join(run, 'failure.json'), JSON.stringify({ classification: 'UNKNOWN', error: error.message, live: 'NOT_RUN' }, null, 2));
    throw error;
  }
}

// No mode in this Node entry point launches --live, opens a socket, or requests elevation.
if (require.main === module) {
  try {
    const args = process.argv.slice(2);
    assert.ok(args.length === 1 && ['--static', '--prepare'].includes(args[0]), 'Syntax: node test/windows-wfp-localhost-poc.probe.cjs --static|--prepare');
    const checks = staticChecks();
    console.log(JSON.stringify(args[0] === '--prepare' ? prepare() : checks, null, 2));
  } catch (error) { console.error(error.message); process.exitCode = 1; }
}
module.exports = { receipt, staticChecks, validateFilterDiagnostic };
